/**
 * The curated icon set for app and folder tiles, hand-picked from lucide-react
 * and grouped for the picker. An icon is stored as `lucide:<name>` where
 * <name> is lucide's own kebab-case id (the same id every lucide port uses,
 * so another client can map it without a table of ours). Named imports keep
 * the bundle to these icons only.
 *
 * Adding one: import it, add it to a category. Removing one is safe: a stored
 * name this map no longer knows renders the default tile.
 */
import {
  Activity,
  Anchor,
  AppWindow,
  Archive,
  Atom,
  Award,
  Binary,
  Bird,
  Book,
  BookMarked,
  BookOpen,
  Bot,
  BrainCircuit,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Cable,
  Cake,
  Calculator,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  Cat,
  ChartArea,
  ChartBar,
  ChartGantt,
  ChartLine,
  ChartPie,
  ChartScatter,
  CircuitBoard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudSun,
  Coffee,
  Cog,
  Compass,
  Construction,
  Contact,
  Cpu,
  Crown,
  Database,
  DatabaseZap,
  Dice5,
  Dog,
  DraftingCompass,
  Droplets,
  Earth,
  Factory,
  Feather,
  FileChartColumn,
  FileCheck,
  FileDiff,
  FilePen,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Files,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderKanban,
  FolderOpen,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitCompare,
  Globe,
  Hammer,
  Handshake,
  HardDrive,
  HardHat,
  Hash,
  Heart,
  Hospital,
  House,
  Inbox,
  Kanban,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  ListTodo,
  Mail,
  Map,
  MapPin,
  Medal,
  MessagesSquare,
  Microchip,
  Microscope,
  Milestone,
  Moon,
  Mountain,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Orbit,
  Palette,
  Paperclip,
  PartyPopper,
  Percent,
  Pipette,
  Pizza,
  Plane,
  Plug,
  Presentation,
  Puzzle,
  Quote,
  Rabbit,
  Radiation,
  Rainbow,
  Rocket,
  Route,
  Router,
  Ruler,
  ScanSearch,
  School,
  ScrollText,
  SearchCheck,
  Server,
  Settings2,
  Sheet,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Sigma,
  Signature,
  Smile,
  Snowflake,
  Sparkles,
  Stamp,
  Star,
  StickyNote,
  Store,
  Sun,
  Table2,
  Target,
  TestTube,
  Thermometer,
  Timer,
  Train,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  UserCheck,
  Users,
  Wand2,
  Warehouse,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const APP_ICONS: Record<string, LucideIcon> = {
  'app-window': AppWindow,
  'layout-dashboard': LayoutDashboard,
  briefcase: Briefcase,
  'clipboard-list': ClipboardList,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  'list-todo': ListTodo,
  kanban: Kanban,
  'calendar-days': CalendarDays,
  'calendar-clock': CalendarClock,
  timer: Timer,
  clock: Clock,
  target: Target,
  flag: Flag,
  milestone: Milestone,
  presentation: Presentation,
  'folder-kanban': FolderKanban,
  inbox: Inbox,
  mail: Mail,
  'messages-square': MessagesSquare,
  users: Users,
  'user-check': UserCheck,
  contact: Contact,
  handshake: Handshake,
  'building-2': Building2,
  landmark: Landmark,
  'table-2': Table2,
  database: Database,
  'database-zap': DatabaseZap,
  sheet: Sheet,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-area': ChartArea,
  'chart-scatter': ChartScatter,
  'chart-gantt': ChartGantt,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  activity: Activity,
  gauge: Gauge,
  sigma: Sigma,
  calculator: Calculator,
  percent: Percent,
  hash: Hash,
  binary: Binary,
  filter: Filter,
  'search-check': SearchCheck,
  'scan-search': ScanSearch,
  'file-spreadsheet': FileSpreadsheet,
  'file-chart-column': FileChartColumn,
  layers: Layers,
  'layout-grid': LayoutGrid,
  wrench: Wrench,
  hammer: Hammer,
  cog: Cog,
  'settings-2': Settings2,
  factory: Factory,
  pipette: Pipette,
  thermometer: Thermometer,
  flame: Flame,
  droplets: Droplets,
  zap: Zap,
  plug: Plug,
  cable: Cable,
  cpu: Cpu,
  'circuit-board': CircuitBoard,
  microchip: Microchip,
  router: Router,
  server: Server,
  'hard-drive': HardDrive,
  network: Network,
  workflow: Workflow,
  route: Route,
  'git-branch': GitBranch,
  'git-compare': GitCompare,
  ruler: Ruler,
  'drafting-compass': DraftingCompass,
  construction: Construction,
  'hard-hat': HardHat,
  'triangle-alert': TriangleAlert,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  bug: Bug,
  microscope: Microscope,
  'flask-conical': FlaskConical,
  'test-tube': TestTube,
  atom: Atom,
  radiation: Radiation,
  orbit: Orbit,
  'file-text': FileText,
  files: Files,
  'file-search': FileSearch,
  'file-check': FileCheck,
  'file-diff': FileDiff,
  'file-pen': FilePen,
  book: Book,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  library: Library,
  notebook: Notebook,
  'notebook-pen': NotebookPen,
  'scroll-text': ScrollText,
  newspaper: Newspaper,
  'sticky-note': StickyNote,
  archive: Archive,
  folder: Folder,
  'folder-open': FolderOpen,
  paperclip: Paperclip,
  stamp: Stamp,
  signature: Signature,
  quote: Quote,
  map: Map,
  'map-pin': MapPin,
  compass: Compass,
  globe: Globe,
  earth: Earth,
  navigation: Navigation,
  truck: Truck,
  car: Car,
  plane: Plane,
  ship: Ship,
  train: Train,
  warehouse: Warehouse,
  store: Store,
  house: House,
  hospital: Hospital,
  school: School,
  'tree-pine': TreePine,
  mountain: Mountain,
  rocket: Rocket,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  smile: Smile,
  lightbulb: Lightbulb,
  puzzle: Puzzle,
  'gamepad-2': Gamepad2,
  'dice-5': Dice5,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  crown: Crown,
  gem: Gem,
  palette: Palette,
  brush: Brush,
  music: Music,
  camera: Camera,
  film: Film,
  coffee: Coffee,
  pizza: Pizza,
  cake: Cake,
  'party-popper': PartyPopper,
  gift: Gift,
  leaf: Leaf,
  'flower-2': Flower2,
  sun: Sun,
  moon: Moon,
  'cloud-sun': CloudSun,
  snowflake: Snowflake,
  rainbow: Rainbow,
  bird: Bird,
  cat: Cat,
  dog: Dog,
  fish: Fish,
  rabbit: Rabbit,
  anchor: Anchor,
  feather: Feather,
  ghost: Ghost,
  bot: Bot,
  'brain-circuit': BrainCircuit,
  'wand-2': Wand2,
};

export const APP_ICON_CATEGORIES: Array<{ label: string; names: string[] }> = [
  {
    label: 'Work',
    names: [
      'app-window',
      'layout-dashboard',
      'briefcase',
      'clipboard-list',
      'clipboard-check',
      'list-checks',
      'list-todo',
      'kanban',
      'calendar-days',
      'calendar-clock',
      'timer',
      'clock',
      'target',
      'flag',
      'milestone',
      'presentation',
      'folder-kanban',
      'inbox',
      'mail',
      'messages-square',
      'users',
      'user-check',
      'contact',
      'handshake',
      'building-2',
      'landmark',
    ],
  },
  {
    label: 'Data',
    names: [
      'table-2',
      'database',
      'database-zap',
      'sheet',
      'chart-bar',
      'chart-line',
      'chart-pie',
      'chart-area',
      'chart-scatter',
      'chart-gantt',
      'trending-up',
      'trending-down',
      'activity',
      'gauge',
      'sigma',
      'calculator',
      'percent',
      'hash',
      'binary',
      'filter',
      'search-check',
      'scan-search',
      'file-spreadsheet',
      'file-chart-column',
      'layers',
      'layout-grid',
    ],
  },
  {
    label: 'Engineering',
    names: [
      'wrench',
      'hammer',
      'cog',
      'settings-2',
      'factory',
      'pipette',
      'thermometer',
      'flame',
      'droplets',
      'zap',
      'plug',
      'cable',
      'cpu',
      'circuit-board',
      'microchip',
      'router',
      'server',
      'hard-drive',
      'network',
      'workflow',
      'route',
      'git-branch',
      'git-compare',
      'ruler',
      'drafting-compass',
      'construction',
      'hard-hat',
      'triangle-alert',
      'shield-check',
      'shield-alert',
      'bug',
      'microscope',
      'flask-conical',
      'test-tube',
      'atom',
      'radiation',
      'orbit',
    ],
  },
  {
    label: 'Documents',
    names: [
      'file-text',
      'files',
      'file-search',
      'file-check',
      'file-diff',
      'file-pen',
      'book',
      'book-open',
      'book-marked',
      'library',
      'notebook',
      'notebook-pen',
      'scroll-text',
      'newspaper',
      'sticky-note',
      'archive',
      'folder',
      'folder-open',
      'paperclip',
      'stamp',
      'signature',
      'quote',
    ],
  },
  {
    label: 'Places',
    names: [
      'map',
      'map-pin',
      'compass',
      'globe',
      'earth',
      'navigation',
      'truck',
      'car',
      'plane',
      'ship',
      'train',
      'warehouse',
      'store',
      'house',
      'hospital',
      'school',
      'tree-pine',
      'mountain',
    ],
  },
  {
    label: 'Fun',
    names: [
      'rocket',
      'sparkles',
      'star',
      'heart',
      'smile',
      'lightbulb',
      'puzzle',
      'gamepad-2',
      'dice-5',
      'trophy',
      'medal',
      'award',
      'crown',
      'gem',
      'palette',
      'brush',
      'music',
      'camera',
      'film',
      'coffee',
      'pizza',
      'cake',
      'party-popper',
      'gift',
      'leaf',
      'flower-2',
      'sun',
      'moon',
      'cloud-sun',
      'snowflake',
      'rainbow',
      'bird',
      'cat',
      'dog',
      'fish',
      'rabbit',
      'anchor',
      'feather',
      'ghost',
      'bot',
      'brain-circuit',
      'wand-2',
    ],
  },
];
